reddit_subreddits:
  - netsec
  - cybersecurity
  # Add more subreddits as needed
websites:
  tomshardware: https://www.tomshardware.com
  arstechnica: http://feeds.arstechnica.com
  # Add more RSS feeds as needed